# MySQL.  Versions 4.1 and 5.0 are recommended.# 
# Install the MYSQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem 'mysql2'
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html

development:
  adapter: mysql2
  encoding: utf8
  database: twitter_app
  username: root
  password: my_password
  host: 127.0.0.1
  port: 3306

production: 
  adapter: mysql2
  database: production
  username: production
  host: 
  password:
  port: 3306
  pool: 40
  timeout: 5000

test:
  adapter: mysql2
  encoding: utf8
  database: twitter_app_test
  username: root
  password: my_password
  host: 127.0.0.1
  port: 3306

