# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ac505952677b5d156ad4dd7a4b87ff8aeccb90fca81dca753a72f6b16c8917e0456e10697f7f7992614f9aa0d3ae6d57a3de1c453c400d6a009fd77e095a9e5

test:
  secret_key_base: 64a7a1e3ce71a6c1aa58a9be04f6ff1c0e2ff69044cc91d8ae0dfa4fc147064067700b25cc025ce5881454aaf7e24f3f3c8c93f232a5bf0204e7e81eb18db686

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
